routes/web.php
<?php

use App\Http\Controllers\CalonController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PenerimaController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\AnalisisController;
use App\Http\Controllers\CalonPenerimaController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\AkunController;
use App\Http\Controllers\TetapkanController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', [HomeController::class, 'index'])->name('auth');
// Route::prefix('')->group(function () {

Auth::routes();
// });
Route::group(['middleware' => ['auth']], function () {
    //Route Home
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::resource('/user', UserController::class);
});

Route::group(['middleware' => ['auth', 'role: 1,2']], function () {
    Route::resource('data-penerima', PenerimaController::class);
    Route::resource('data-calon', CalonController::class);
    Route::resource('profile', ProfileController::class);
    // Route::get('/profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::resource('settings', SettingsController::class);
    Route::get('/ubah-password/{id}', [SettingsController::class, 'edit'])->name('settings.edit');
    Route::put('/ubah-password/{id}', [SettingsController::class, 'update'])->name('settings.update');
    // Route::post('/penerima/tetapkan', [PenerimaController::class, 'tetapkan'])->name('penerima.tetapkan');
    // Route::get('/settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::get('/calon', [CalonPenerimaController::class, 'index']);
    Route::get('/calon/export_excel', [CalonPenerimaController::class, 'export_excel']);
    Route::post('/calon/import_excel', [CalonPenerimaController::class, 'import_excel']);
    Route::post('/calon/tetapkan', [CalonPenerimaController::class, 'tetapkan']);
    Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan.index');
    Route::get('/laporan/cetak_pdf', [LaporanController::class, 'cetak_pdf'])->name('laporan.cetak_pdf');

    Route::group(['middleware' => 'auth'], function () {
        Route::get('/changePassword', [App\Http\Controllers\changePassword::class, 'showChangePasswordGet'])->name('changePasswordGet');
        Route::post('/changePassword', [App\Http\Controllers\changePassword::class, 'changePasswordPost'])->name('changePasswordPost');
    });
});


Route::group(['middleware' => ['auth', 'role: 1']], function () {
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('analisis', AnalisisController::class);
    Route::resource('kelola-akun', AkunController::class);
    Route::get('/kelola-akun', [SettingsController::class, 'kelola'])->name('settings.kelola');
});

resources/views/data-calon.blade.php
@extends('partial.master') @section('content')
<section class="section">
  <div class="section-header">
    <h1>Data Calon Penerima</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{{ route('dashboard') }}">Dashboard</a></div>
      <div class="breadcrumb-item">Data Calon</div>
    </div>
  </div>
  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header col-12">
            <h4 class="m-lg-0 col-10 text-left">
              Kelola Data Calon Penerima
            </h4>
            <button type="button" class="btn btn-success col-2" data-toggle="modal" data-target="#modalAlertImportCalon">
              <i class="fas fa-file-excel"></i>Import Excel
            </button>
          </div>
          <div class="card-body icon-right">
            <a href="{{ route('data-calon.create') }}" class="col-2 btn btn-icon icon-left btn-primary"><i class="fas fa-plus"></i>Tambah Data</a>
            <!-- <a href="tambah-data-calon.html" class="col-2 btn btn-icon icon-left btn-primary"><i class="fas fa-file-alt"></i>Update Data</a> -->
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped" id="table-1">
                <thead>
                  <tr>
                    <th width="15%">No. KK</th>
                    <th width="15%">NIK</th>
                    <th width="20%">Nama KK</th>
                    <th width="10%">Jenis Kelamin</th>
                    <th width="10%">Dusun</th>
                    <th width="5%">RT</th>
                    <th width="5%">RW</th>
                    <th width="15%">Aksi</th>
                  </tr>
                </thead>
                <tbody>
                  @forelse ($calon as $key=>$data)
                  <tr>
                    <td>{{ $data->no_kk }}</td>
                    <td>{{ $data->nik }}</td>
                    <td>{{ $data->nama_kk }}</td>
                    <td>{{ $data->jk }}</td>
                    <td>{{ $data->dusun }}</td>
                    <td>{{ $data->rt }}</td>
                    <td>{{ $data->rw }}</td>
                    <td>
                      <form action="{{route('data-calon.destroy', $data->id)}}" method="POST">
                        @csrf @method('DELETE')
                        <a href="{{ route('data-calon.show', $data->id)}}" class="btn btn-icon btn-info"><i class="fas fa-info-circle"></i></a>
                        <a href="{{ route('data-calon.edit', $data->id)}}" class="btn btn-icon btn-primary"><i class="fas fa-pen-square"></i></a>
                        <button type="submit" class="btn btn-icon btn-danger" value="Delete">
                          <i class="fas fa-trash"></i>
                        </button>
                      </form>
                    </td>
                  </tr>
                  @empty
                  <tr>
                    <td colspan="4">DATA KOSONG!</td>
                  </tr>
                  @endforelse
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/data-penerima.blade.php
@extends('partial.master')
@section('content')
<section class="section">
  <div class="section-header">
    <h1>Data Penerima</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{{ route('dashboard') }}">Dashboard</a></div>
      <div class="breadcrumb-item">Data Penerima</div>
    </div>
  </div>
  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4>Kelola Data Penerima</h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped" id="table-1">
                <thead>
                  <tr>
                    <th>No. KK</th>
                    <th>NIK</th>
                    <th>Nama KK</th>
                    <th>Jenis Kelamin</th>
                    <th>Dusun</th>
                    <th>RT</th>
                    <th>RW</th>
                    <th>Status</th>
                    <th>Tahun</th>
                    <th>Aksi</th>
                  </tr>
                </thead>
                <tbody>
                  @forelse ($penerima as $key=>$data)
                  <tr>
                    <td>{{ $data->no_kk }}</td>
                    <td>{{ $data->nik }}</td>
                    <td>{{ $data->nama_kk }}</td>
                    <td>{{ $data->jk }}</td>
                    <td>{{ $data->dusun }}</td>
                    <td>{{ $data->rt }}</td>
                    <td>{{ $data->rw }}</td>
                    <td>{{ $data->status }}</td>
                    <td>{{ date('Y', strtotime($data["updated_at"])) }}</td>
                    <td>
                      <form action="{{route('data-penerima.destroy', $data->id)}}">
                        @csrf
                        <a href="{{ route('data-penerima.show', $data->id)}}" class="btn btn-icon btn-info"><i class="fas fa-info-circle"></i></a>
                        </button>
                      </form>
                    </td>
                  </tr>
                  @empty
                  <tr>
                    <td colspan="4">DATA KOSONG!</td>
                  </tr>
                  @endforelse
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/detail-calon.blade.php
@extends('partial.master')
@section('content')
<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center"></div>
                        <h1 class="h3 mb-2 text-gray-800">Detail Data Calon</h1>
                    </div>
                    <div class="card-body">
                        <p>No KK : {{ $calon->no_kk }}</p>
                        <p>NIK : {{ $calon->nik }}</p>
                        <p>Nama : {{ $calon->nama_kk }}</p>
                        <p>Jenis Kelamin : {{ $calon->jk }}</p>
                        <p>Dusun : {{ $calon->dusun }}</p>
                        <p>RT : {{ $calon->rt }}</p>
                        <p>RW : {{ $calon->rw }}</p>
                        <p>Tanggungan : {{ $calon->tanggungan }}</p>
                        <p>Pekerjaan : {{ $calon->pekerjaan }}</p>
                        <p>Penghasilan : {{ $calon->penghasilan }}</p>
                        <p>Jenis Lantai : {{ $calon->jenis_lantai }}</p>
                        <p>Jenis Dinding : {{ $calon->jenis_dinding }}</p>
                        <p>Sumber Listrik : {{ $calon->sumber_listrik }}</p>
                        <p>Sumber Air : {{ $calon->sumber_air }}</p>
                        <p>Status Kepemilikan MCK : {{ $calon->sk_mck }}</p>
                        <p>Status Kepemilikan Rumah : {{ $calon->sk_rumah }}</p>
                        <a class="btn btn-primary" href="{{ route('data-calon.index') }}">Kembali</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/kelola-akun.blade.php
@extends('partial.master') @section('content')
<section class="section">
    <div class="section-header">
        <h1>Kelola User</h1>
        <div class="section-header-breadcrumb">
            <div class="breadcrumb-item active"><a href="{{ route('dashboard') }}">Dashboard</a></div>
            <div class="breadcrumb-item">Kelola User</div>
        </div>
    </div>
    <div class="section-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header col-12">
                        <h4 class="m-lg-0 col-10 text-left">
                            Kelola Data User
                        </h4>
                        <a href="{{ route('kelola-akun.create') }}" class="col-2 btn btn-icon icon-left btn-primary"><i class="fas fa-plus"></i>Tambah User
                        </a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped" id="table-1">
                                <thead>
                                    <tr>
                                        <th width="10%">Role</th>
                                        <th width="20%">Nama</th>
                                        <th width="20%">Jabatan</th>
                                        <th width="15%">Telepon</th>
                                        <th width="20%">Email</th>
                                        <th width="15%">Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($akun as $key=>$data)
                                    <tr>
                                        <td>{{ $data->roles->nm_roles}}</td>
                                        <td>{{ $data->nama }}</td>
                                        <td>{{ $data->jabatan }}</td>
                                        <td>{{ $data->telepon }}</td>
                                        <td>{{ $data->email }}</td>
                                        <th scope="col">
                                            <form action="{{route('kelola-akun.destroy', $data->id)}}" method="POST">
                                                @csrf @method('DELETE')
                                                <center>
                                                    <a href="{{ route('kelola-akun.edit', $data->id)}}" class="btn btn-icon btn-primary"><i class="fas fa-pen-square"></i></a>
                                                    <button type="submit" class="btn btn-icon btn-danger" value="Delete">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </center>
                                            </form>
                                        </th>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="4">DATA KOSONG!</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/kriteria.blade.php
@extends('partial.master')
@section('content')
<section class="section">
  <div class="section-header">
    <h1>Data Kriteria</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{{ route('dashboard') }}">Dashboard</a></div>
      <div class="breadcrumb-item">Kriteria</div>
    </div>
  </div>
  <div class="section-body">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h4 class="m-lg-0 col-10 text-left ">Kelola Data Kriteria</h4>
            <a href="{{ route('kriteria.create') }}" class="col-2 btn btn-icon icon-left btn-primary">
              <i class="fas fa-plus"></i>Tambah Kategori
            </a>
          </div>
          <div class="card-body">
            <div class="card-body">
              @foreach ($orders as $key=>$data)
              <div id="accordion">
                <div class="accordion">
                  <div class="accordion-header" role="button" data-toggle="collapse" data-target="#panel-body-1" aria-expanded="true">
                    <h4>Jenis Kriteria : {{ $data->jenis_kriteria }}</h4>
                  </div>
                  <div class="accordion-body " id="panel-body-1" data-parent="#accordion">
                    <table class="table table-bordered">
                      <thead>
                        <tr>
                          <th width="20%" scope="col">
                            <center>Kode Kriteria</center>
                          </th>
                          <th width="50%" scope="col">
                            <center>Nama Kriteria</center>
                          </th>
                          <th width="30%" scope="col">
                            <center>Aksi</center>
                          </th>
                        </tr>
                      </thead>
                      <tbody>

                        @foreach ($kriteria as $key2=>$data2)
                        <?php if ($data->jenis_kriteria == $data2->jenis_kriteria) { ?>
                          <tr>
                            <td scope="col">
                              <center>{{ $data2->kode_kriteria }}</center>
                            </td>
                            <td scope="col">{{ $data2->nama_kriteria }}</td>
                            <td scope="col">
                              <form action="{{route('kriteria.destroy', $data2->id)}}" method="POST">
                                @csrf @method('DELETE')
                                <center>
                                  <a href="{{ route('kriteria.edit', $data2->id)}}" class="btn btn-icon btn-primary"><i class="fas fa-pen-square"></i></a>
                                  <button type="submit" class="btn btn-icon btn-danger" value="Delete">
                                    <i class="fas fa-trash"></i>
                                  </button>
                                </center>
                              </form>
                            </td>
                          </tr>
                        <?php } ?>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
                @endforeach
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/profile.blade.php
@extends('partial.master')
@section('content')
<section class="section">
  <div class="section-header">
    <h1>Profile</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{{ route('dashboard') }}">Dashboard</a></div>
      <div class="breadcrumb-item">Profile</div>
    </div>
  </div>
  <div class="section-body">
    <h2 class="section-title">Hi, {{ Auth::user()->nama }}!</h2>
    <p class="section-lead">
      Ini merupakan halaman data diri anda.
    </p>
    <div class="row mt-sm-4">
      <div class="col-12 col-md-12 col-lg-5">
        <div class="card profile-widget">
          <div class="profile-widget-header">
            <img alt="image" src="assets/img/avatar/avatar-1.png" class="rounded-circle profile-widget-picture">
          </div>
          <div class="profile-widget-description">
            <div class="profile-widget-name">{{ Auth::user()->nama }}
              <div class="text-muted d-inline font-weight-normal">
                <div class="slash"></div>{{ Auth::user()->roles->nm_roles }}
              </div>
            </div>
            <div class="profile-widget-name">{{ Auth::user()->jabatan }}</div>
          </div>
          <div class="card-footer text-right">
            <a href="{{ route('profile.edit', Auth::user()->id) }}" class="btn btn-primary" id="save-btn">Edit</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
@endsection

resources/views/ubah-data-calon.blade.php
@extends('partial.master')
@section('content')
<section class="section">
  <div class="section-header">
    <div class="section-header-back">
      <a href="{{ route('data-calon.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
    </div>
    <h1>Ubah Data Calon</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="{{ route('dashboard') }}">Dashboard</a></div>
      <div class="breadcrumb-item active"><a href="{{ route('data-calon.index') }}">Data Calon</a></div>
      <div class="breadcrumb-item">Ubah Data Calon</div>
    </div>
  </div>

  <div class="section-body">
    <h2 class="section-title">Ubah Data Calon Penerima</h2>
    <p class="section-lead">
      Ini merupakan halaman untuk mengubah data masyarakat calon penerima bantuan.
    </p>
    <div id="output-status"></div>
    <div class="row">
      <div class="col-md-10">
        <div class="card" id="settings-card">
          <div class="card-header">
            <h4>Form Edit Data</h4>
          </div>
          <div class="card-body">
            <form action="{{ route('data-calon.update', $calon->id) }}" method="POST">
              @csrf
              @method('PUT')
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label>NO. KK</label>
                  <input type="text" name="no_kk" class="form-control @error('no_kk') is-invalid @enderror" placeholder="No. Kartu Keluarga" value="{{old('no_kk', $calon->no_kk)}}">
                  @error('no_kk')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group col-md-6">
                  <label>NIK Kepala Keluarga</label>
                  <input type="text" name="nik" class="form-control @error('nik') is-invalid @enderror" placeholder="NIK" value="{{old('nik', $calon->nik)}}">
                  @error('nik')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-8">
                  <label>Nama Kepala Keluarga</label>
                  <input type="text" name="nama_kk" class="form-control @error('nama_kk') is-invalid @enderror" placeholder="Nama Kepala Keluarga" value="{{old('nama_kk', $calon->nama_kk)}}">
                  @error('nama_kk')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group col-md-4">
                  <label>Jenis Kelamin</label>
                  <select name="jk" class="form-control @error('jk') is-invalid @enderror" value="{{old('jk', $calon->jk)}}">
                    <option selected>{{old('jk', $calon->jk)}}</option>
                    <option>Laki-Laki</option>
                    <option>Perempuan</option>
                  </select>
                  @error('jk')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label>Dusun</label>
                  <select name="dusun" class="form-control @error('dusun') is-invalid @enderror" value="{{old('dusun', $calon->dusun)}}">
                    <option selected>{{old('dusun', $calon->dusun)}}</option>
                    <option>Mekarmulya</option>
                    <option>Mawarsari</option>
                    <option>Mekarsari</option>
                    <option>Huludayeuh</option>
                    <option>Babakan Indah</option>
                    <option>Cangkore</option>
                  </select>
                  @error('dusun')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group col-md-2">
                  <label>Rt</label>
                  <input type="text" name="rt" class="form-control @error('rt') is-invalid @enderror" placeholder="RT" value="{{old('rt', $calon->rt)}}">
                  @error('rt')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group col-md-2">
                  <label>Rw</label>
                  <input type="text" name="rw" class="form-control @error('rw') is-invalid @enderror" placeholder="RW" value="{{old('rw', $calon->rw)}}">
                  @error('rw')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-2">
                  <label>Tanggungan</label>
                  <select name="tanggungan" class="form-control @error('tanggungan') is-invalid @enderror" value="{{old('tanggungan', $calon->tanggungan)}}">
                    <option selected>{{old('tanggungan', $calon->tanggungan)}}</option>
                    @foreach ($tanggungan as $key2=>$data2)
                    <?php if ($data2->jenis_kriteria) { ?>
                      <option>{{ $data2->nama_kriteria }}</option>
                    <?php } ?>
                    @endforeach
                  </select>
                  @error('tanggungan')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group col-md-5">
                  <label>Pekerjaan</label>
                  <select name="pekerjaan" class="form-control @error('pekerjaan') is-invalid @enderror" value="{{old('pekerjaan', $calon->pekerjaan)}}">
                    <option selected>{{old('pekerjaan', $calon->pekerjaan)}}</option>
                    @foreach ($pekerjaan as $key2=>$data2)
                    <?php if ($data2->jenis_kriteria) { ?>
                      <option>{{ $data2->nama_kriteria }}</option>
                    <?php } ?>
                    @endforeach
                  </select>
                  @error('pekerjaan')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group col-md-5">
                  <label>Penghasilan</label>
                  <select name="penghasilan" class="form-control  @error('penghasilan') is-invalid @enderror" value="{{old('penghasilan', $calon->penghasilan)}}">
                    <option selected>{{old('penghasilan', $calon->penghasilan)}}</option>
                    @foreach ($penghasilan as $key2=>$data2)
                    <?php if ($data2->jenis_kriteria) { ?>
                      <option>{{ $data2->nama_kriteria }}</option>
                    <?php } ?>
                    @endforeach
                  </select>
                  @error('penghasilan')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label>Jenis Lantai</label>
                  <select name="jenis_lantai" class="form-control  @error('jenis_lantai') is-invalid @enderror" value="{{old('jenis_lantai', $calon->jenis_lantai)}}">
                    <option selected>{{old('jenis_lantai', $calon->jenis_lantai)}}</option>
                    @foreach ($jl as $key2=>$data2)
                    <?php if ($data2->jenis_kriteria) { ?>
                      <option>{{ $data2->nama_kriteria }}</option>
                    <?php } ?>
                    @endforeach
                  </select>
                  @error('jenis_lantai')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group col-md-6">
                  <label>Jenis Dinding</label>
                  <select name="jenis_dinding" class="form-control  @error('jenis_dinding') is-invalid @enderror" value="{{old('jenis_dinding', $calon->jenis_dinding)}}">
                    <option selected>{{old('jenis_dinding', $calon->jenis_dinding)}}</option>
                    @foreach ($jd as $key2=>$data2)
                    <?php if ($data2->jenis_kriteria) { ?>
                      <option>{{ $data2->nama_kriteria }}</option>
                    <?php } ?>
                    @endforeach
                  </select>
                  @error('jenis_dinding')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label>Sumber Air</label>
                  <select name="sumber_air" class="form-control  @error('sumber_air') is-invalid @enderror" value="{{old('sumber_air', $calon->sumber_air)}}">
                    <option selected>{{old('sumber_air', $calon->sumber_air)}}</option>
                    @foreach ($sa as $key2=>$data2)
                    <?php if ($data2->jenis_kriteria) { ?>
                      <option>{{ $data2->nama_kriteria }}</option>
                    <?php } ?>
                    @endforeach
                  </select>
                  @error('sumber_air')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group col-md-6">
                  <label>Sumber Listrik</label>
                  <select name="sumber_listrik" class="form-control  @error('sumber_listrik') is-invalid @enderror" value="{{old('sumber_listrik', $calon->sumber_listrik)}}">
                    <option selected>{{old('sumber_listrik', $calon->sumber_listrik)}}</option>
                    @foreach ($sl as $key2=>$data2)
                    <?php if ($data2->jenis_kriteria) { ?>
                      <option>{{ $data2->nama_kriteria }}</option>
                    <?php } ?>
                    @endforeach
                  </select>
                  @error('sumber_listrik')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label>Status Kepemilikan MCK</label>
                  <select name="sk_mck" class="form-control  @error('sk_mck') is-invalid @enderror" value="{{old('sk_mck', $calon->sk_mck)}}">
                    <option selected>{{old('sk_mck', $calon->sk_mck)}}</option>
                    @foreach ($mck as $key2=>$data2)
                    <?php if ($data2->jenis_kriteria) { ?>
                      <option>{{ $data2->nama_kriteria }}</option>
                    <?php } ?>
                    @endforeach
                  </select>
                  @error('sk_mck')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group col-md-6">
                  <label>Status Kepemilikan Rumah</label>
                  <select name="sk_rumah" class="form-control  @error('sk_rumah') is-invalid @enderror">
                    <option selected>{{old('sk_rumah', $calon->sk_rumah)}}</option>
                    @foreach ($rumah as $key2=>$data2)
                    <?php if ($data2->jenis_kriteria) { ?>
                      <option>{{ $data2->nama_kriteria }}</option>
                    <?php } ?>
                    @endforeach
                  </select>
                  @error('sk_rumah')
                  <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
              </div>
              <div class="card-footer bg-whitesmoke text-md-right">
                <button type="submit" class="btn btn-primary" id="save-btn">Simpan</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</section>
@endsection